---
title: "Vis Assignment 4"
author: "Marissa Getts"
date: "10/6/2020"
output: html_document
---
## Off-leash Dog Parks in Boise, Idaho

 Important: Julia Meinhardt helped me out SO MUCH in troubleshooting/debugging my code. Could not have done this assignment without her help! 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
```

```{r}
dog <- read_sf("https://opendata.arcgis.com/datasets/6b070c12969b4b32990a8481b0c074bb_0.kml",
  quiet = TRUE)
```

```{r}
opq(bbox = 'Boise ID USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_xml(file = 'OTP/graphs/default/boise_streets.osm')
```

```{r}
ID_state_plane <- "+proj=tmerc +lat_0=41.66666666666666 +lon_0=-114 +k=0.9999473679999999 +x_0=500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"

boise_street_features <- opq(bbox = 'Boise ID USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

boise_streets <- boise_street_features$osm_lines %>%
  st_transform(crs = ID_state_plane)
```

```{r}
ggplot(boise_streets) +
  geom_sf() +
  theme_map()
```
```{r}
path_otp <- otp_dl_jar("OTP")

```
```{r, results=FALSE}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```

```{r}
otp_setup(otp = path_otp, dir = path_data, memory =1024)
```
```{r}
otpcon <- otp_connect()

```

```{r, results=FALSE}
iso_5min_walk_m <- 
  otp_isochrone(otpcon = otpcon, fromPlace = dog, 
                mode = "WALK", cutoffSec = 300) %>%
                st_transform(crs = ID_state_plane) %>%
                mutate(mode = "walk")

iso_5min_drive_m <- 
  otp_isochrone(otpcon = otpcon, fromPlace = dog, 
                mode = "CAR", cutoffSec = 300) %>%
                st_transform(crs = ID_state_plane) %>%
                mutate(mode = "drive")

iso_all_modes_m <- rbind(iso_5min_drive_m, iso_5min_walk_m)

```
```{r}
right_side <- st_bbox(iso_all_modes_m)$xmax
left_side  <- st_bbox(iso_all_modes_m)$xmin
top_side <- st_bbox(iso_all_modes_m)$ymax
bottom_side <- st_bbox(iso_all_modes_m)$ymin

ggplot(iso_all_modes_m) +
  annotation_map_tile(zoomin = 0, progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
   coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  geom_sf(data = dog) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car", "By foot")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```


```{r}
iso_areas <- iso_all_modes_m %>%
  mutate(area = st_area(iso_all_modes_m)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a five-minute walking distance\nof an off-leash dog park\n(square km)",
            breaks = breaks <- seq(000, 800000, by = 10000),
            labels = breaks / 1000) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof an off leash dog park\n(square km)",
           breaks = breaks <- seq(0, 1300000, by = 100000),
            labels = breaks / 10000) +
  theme_bw()
```
```{r, include=FALSE}
library(wesanderson)
```


```{r}
iso_areas_2 <- data.frame(mode = rep(c("Bicycle", "Walk"), each = 14),
                          dog =rep(c("1",
                              "2",
                              "3",
                              "4",
                              "5",
                              "6",
                              "7",
                              "8",
                              "9",
                              "10",
                              "11",
                              "12",
                              "13",
                              "14")),
                          area = c(iso_areas$drive, iso_areas$walk))
ggplot(iso_areas_2,
       aes(x = as.numeric(area) , y = dog, fill = mode)) +
  geom_bar(stat = "identity", width = 0.5, position = "dodge") +
  scale_x_continuous(name = "Area Covered (square km)",
                     breaks = breaks <- seq(0000, 8000000, by = 100000),
                     labels = breaks / 100000) +
  scale_y_discrete(name = "Boulder")+
  scale_fill_manual(name = "Area Covered by Driving and Walking",
                    values = wes_palette("FantasticFox1", 2, type = c("discrete")),
                    labels = c("Driving",
                               "Walk")) +
  labs(title = "Isochrome Area Calculations for Off-Leash Dog Parks in Boise Idaho")+
  theme_minimal()
```

